name: Deploy Rules

on:
  push:
    branches:
      - develop
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set profile based on branch
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
              echo "spring.profiles.active=dev" > application-dev.yml
              REPO_NAME="alison-jung-dev"
              echo "REPO_NAME set to $REPO_NAME"
            elif [[ ${{ github.ref }} == 'refs/heads/stage' ]]; then
              echo "spring.profiles.active=stage" > application-stg.yml
              REPO_NAME="alison-jung-stg"
              echo "REPO_NAME set to $REPO_NAME"
            elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
              echo "spring.profiles.active=prod" > application-prod.yml
              REPO_NAME="alison-jung-prod"
              echo "REPO_NAME set to $REPO_NAME"
            fi
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build the Docker image
        run: docker build -t deploy-build .

      - name: Tag the Docker image
        run: |
          if [[ -n $REPO_NAME ]]; then
            docker tag deploy-build:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest
          fi

      - name: Push image to ECR
        run: |
          if [[ -n $REPO_NAME ]]; then
            echo "Pushing image to ECR: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest"
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest
          fi
