name: Deploy Rules

on:
  push:
    tags:
      - '*-dev.*'
      - '*-stg.*'
      - '*-prod.*'
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set profile based on tag
        run: |
          if [[ ${{ github.event_name }} == 'push' ]]; then
            if [[ ${{ github.ref }} == 'refs/tags/*-dev.*' ]]; then
              echo "spring.profiles.active=dev" > application-dev.yml
              REPO_NAME="alison-jung-dev"
            elif [[ ${{ github.ref }} == 'refs/tags/*-stg.*' ]]; then
              echo "spring.profiles.active=stage" > application-stg.yml
              REPO_NAME="alison-jung-stg"
            elif [[ ${{ github.ref }} == 'refs/tags/*-prod.*' ]]; then
              echo "spring.profiles.active=prod" > application-prod.yml
              REPO_NAME="alison-jung-prod"
            else
              echo "spring.profiles.active=local" > application-local.yml
              REPO_NAME="alison-jung-local"
            fi
          fi

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com --no-include-email

      - name: Build the Docker image
        run: docker build -t deploy-build .

      - name: Tag the Docker image
        run: |
          docker tag deploy-build:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest

      - name: Push image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${REPO_NAME}:latest
